apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csv-diff-server.fullname" . }}
  labels:
    {{- include "csv-diff-server.labels" . | nindent 4 }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "csv-diff-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "csv-diff-server.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "csv-diff-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      
      {{- if .Values.persistence.enabled }}
      initContainers:
        - name: take-data-dir-ownership
          image: alpine:3
          # Give `grafana` user (id 472) permissions a mounted volume
          # https://github.com/grafana/grafana-docker/blob/master/Dockerfile
          command:
          - chown
          - -R
          - 1001:1001
          - /data/csv-diff-server
          volumeMounts:
            - name: csv-diff-server-data
              mountPath: /data/csv-diff-server
              subPath: csv-diff-server
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:latest"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          # TODO: improve these
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          env:

            # node env
            - name: NODE_ENV
              value: {{ .Values.envVars.nodeEnv }}

            # Paths
            - name: PATHS_DATABASE
              value: {{ .Values.envVars.paths.database }}
            - name: PATHS_DIFF
              value: {{ .Values.envVars.paths.diffs }}

          volumeMounts:
            - name: csv-diff-server-data
              mountPath: /data/csv-diff-server
              subPath: csv-diff-server

      volumes:
        - name: csv-diff-server-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-csv-diff-server" (include "csv-diff-server.fullname" .)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}


      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

