{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csv-diff-server.serviceAccountName" . }}
  labels:
{{ include "csv-diff-server.labels" . | nindent 4 }}
{{- end -}}
